### ISSUE TITLE
NPE in NewlinesRule

### ISSUE THREAD

**Issue by kgevorkyan** [cqfn/diKTat#1047]
Consider the following code:
```kotlin
fun foo() {
    val a = it.responseBody!![0].name
}
```
NPE:

```bash
[ERROR] 2021-09-06 18:22:12 Internal error has occurred in rule [newlines].
Please make an issue on this bug at https://github.com/cqfn/diKTat/. 
As a workaround you can disable these inspections in yml config: <[COMPLEX_EXPRESSION, REDUNDANT_SEMICOLON, WRONG_NEWLINES]>.
java.lang.NullPointerException: astNode.treePrev must not be null 
at org.cqfn.diktat.ruleset.rules.chapter3.files.NewlinesRule.isNotValidCalls(NewlinesRule.kt:557)               
at org.cqfn.diktat.ruleset.rules.chapter3.files.NewlinesRule.isCallsChain(NewlinesRule.kt:532)
at org.cqfn.diktat.ruleset.rules.chapter3.files.NewlinesRule.handleOperatorWithLineBreakBefore(NewlinesRule.kt:186)         
at org.cqfn.diktat.ruleset.rules.chapter3.files.NewlinesRule.logic(NewlinesRule.kt:126)
at org.cqfn.diktat.ruleset.rules.DiktatRule.visit(DiktatRule.kt:50)
at com.pinterest.ktlint.core.KtLint$format$1.invoke(KtLint.kt:271)
at com.pinterest.ktlint.core.KtLint$format$1.invoke(KtLint.kt:23)                  
```

**Comment by petertrr** [comment]
It actually may be a good idea for a new rule to suggest to replace `!! [] ` with `!!.get()`. I think it improves readability, because operators are less explicit than function calls.
