### ISSUE TITLE
Cannot automatically update versions in pom.xml from release workflow

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#108]
```
Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
Push to branch master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 3 of 3 required status checks are expected. At least 1 approving review is required by reviewers with write access.        
To https://github.com/cqfn/diKTat.git
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/cqfn/diKTat.git'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by akuleshov7** [comment]
we will take this task to the next week 
https://developer.github.com/v3/pulls/#create-a-pull-request
https://github.com/peter-evans/create-pull-request

**Comment by akuleshov7** [comment]
also need to update all doc files automatically - simply add "grep" and "sed"

**Comment by petertrr** [comment]
So, the planned workflow will be as follows:
1. After the new version is built and uploaded to maven repo, new git branch is created
2. Development versions are updated in poms
3. Usage version is updated in README
4. Pull request is created
5. Another new branch is created from master
6. `diktat-check.version` is updated to fresh release
7. pull request is opened to allow us to fix code style issues should they arise

@akuleshov7 please confirm. Or have we decided to create single pull request since we have shapshot code style check?
