### ISSUE TITLE
Example from a README doesn't work

### ISSUE THREAD

**Issue by aivinog1** [cqfn/diKTat#243]
When I use diktat of 1.0.2:
```
a.i.vinogradov@vm-dmz-app53 ~ % ktlint -R /usr/local/Cellar/diktat/1.0.2/libexec/diktat.jar "**/*.kt"
Exception in thread "main" java.lang.VerifyError: Cannot inherit from final class
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.cqfn.diktat.ruleset.rules.DiktatRuleSetProvider.get(DiktatRuleSetProvider.kt:32)
        at com.pinterest.ktlint.KtlintCommandLine.loadRulesets(Main.kt:550)
        at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:222)
        at com.pinterest.ktlint.Main.main(Main.kt:62)
```

Mac OS version:
```
a.i.vinogradov@vm-dmz-app53 ~ % sw_vers -productVersion 
10.15.6
a.i.vinogradov@vm-dmz-app53 ~ % 
```

Java version:
```
a.i.vinogradov@vm-dmz-app53 ~ % java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
a.i.vinogradov@vm-dmz-app53 ~ % 
```

Ktlint version:
```
a.i.vinogradov@vm-dmz-app53 diKTat % ktlint --version
0.38.1
a.i.vinogradov@vm-dmz-app53 diKTat % 
```

**Comment by akuleshov7** [comment]
@aivinog1 thank you for your report, we will investigate and fix it this week!

**Comment by akuleshov7** [comment]
Diktat was released to maven central: https://repo.maven.apache.org/maven2/org/cqfn/diktat/
Now there is no dependency on forks. And after we will do testing you will be able to use
`ktlint -R diktat.jar "**/*.kt"` from the https://github.com/cqfn/diKTat/releases/tag/v0.1.0

**Comment by akuleshov7** [comment]
@aivinog1 this is fixed now, thanks. See the latest maven/git release
https://github.com/cqfn/diKTat#run-as-cli-application
