### ISSUE TITLE
KotlinParseException in PACKAGE_NAMING in smoke tests

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#313]
```
Caused by: org.cqfn.diktat.ruleset.utils.KotlinParseException: Your text is not valid: package your.package.name.here.test.smoke
	at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode(KotlinParser.kt:38)
	at org.cqfn.diktat.ruleset.rules.PackageNaming.insertNewPackageName(PackageNaming.kt:204)
	at org.cqfn.diktat.ruleset.rules.PackageNaming.access$insertNewPackageName(PackageNaming.kt:34)
	at org.cqfn.diktat.ruleset.rules.PackageNaming$checkPackageName$3.invoke(PackageNaming.kt:134)
	at org.cqfn.diktat.ruleset.rules.PackageNaming$checkPackageName$3.invoke(PackageNaming.kt:34)
	at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix(Warnings.kt:141)
	at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix$default(Warnings.kt:111)
	at org.cqfn.diktat.ruleset.rules.PackageNaming.checkPackageName(PackageNaming.kt:130)
	at org.cqfn.diktat.ruleset.rules.PackageNaming.visit(PackageNaming.kt:74)
	at com.pinterest.ktlint.core.KtLint$format$1.invoke(KtLint.kt:351)
	... 80 more
```

**Comment by akuleshov7** [comment]
@petertrr I was so LOL when after debugging I understood the issue. 
Kotlin parser has build this kind of a tree:
```
package your.package.name.here.test.smoke
kotlin.FILE: "package your.package.name.here.test.smoke"
- PACKAGE_DIRECTIVE: "package your.package.name.here.test.smoke"
-- package: "package"
-- WHITE_SPACE: " "
-- DOT_QUALIFIED_EXPRESSION: "your.package.name.here.test.smoke"
--- DOT_QUALIFIED_EXPRESSION: "your.package.name.here.test"
---- DOT_QUALIFIED_EXPRESSION: "your.package.name.here"
----- DOT_QUALIFIED_EXPRESSION: "your.package.name"
------ DOT_QUALIFIED_EXPRESSION: "your.package"
------- REFERENCE_EXPRESSION: "your"
-------- IDENTIFIER: "your"
------- DOT: "."
------- ERROR_ELEMENT: "package"
-------- package: "package"
------ DOT: "."
------ REFERENCE_EXPRESSION: "name"
------- IDENTIFIER: "name"
----- DOT: "."
----- REFERENCE_EXPRESSION: "here"
------ IDENTIFIER: "here"
---- DOT: "."
---- REFERENCE_EXPRESSION: "test"
----- IDENTIFIER: "test"
--- DOT: "."
--- REFERENCE_EXPRESSION: "smoke"
---- IDENTIFIER: "smoke"
- IMPORT_LIST: ""
```


And the Error element is ```
------- ERROR_ELEMENT: "package"
-------- package: "package"
```

Haha :) You have forgotten that package is a reserved key word :)))
