### ISSUE TITLE
Indentation bug before closing parentheses

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#377]
```kotlin
fun foo() {
    return x +
            (y +
                    foo(x)
            )
}
```
Indentation rule tries to place `)` 8 spaces to the left.

**Comment by petertrr** [comment]
For diktat 0.1.3 this also causes NPE:
```
Caused by: kotlin.KotlinNullPointerException: null
	at org.cqfn.diktat.ruleset.rules.files.NewlinesRule$handleReturnStatement$$inlined$also$lambda$1.invoke(NewlinesRule.kt:298) ~[diktat-rules-0.1.3.jar:na]
	at org.cqfn.diktat.ruleset.rules.files.NewlinesRule$handleReturnStatement$$inlined$also$lambda$1.invoke(NewlinesRule.kt:98) ~[diktat-rules-0.1.3.jar:na]
	at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix(Warnings.kt:181) ~[diktat-rules-0.1.3.jar:na]

```

**Comment by petertrr** [comment]
NPE is actually thrown only on invalid code: if there is a `return` in a body, there should also be an explicitly specified return type.
