### ISSUE TITLE
NPE in IndentationRule (during autofix)

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#555]
## Describe the bug
```kotlin
fun foo() {
    val diktatExtension = project.extensions.create(DIKTAT_EXTENSION, DiktatExtension::class.java)
    diktatExtension.inputs = project.fileTree("src").apply {
        include("**/*.kt")
    }
    diktatExtension.reporter = PlainReporter(System.out)
}
```
yields
```
Caused by: java.lang.IllegalStateException: whiteSpace.prevSibling must not be null
	at org.cqfn.diktat.ruleset.utils.indentation.AssignmentOperatorChecker.checkNode(Checkers.kt:55) ~[diktat-rules-0.1.4.jar:na]
	at org.cqfn.diktat.ruleset.rules.files.IndentationRule.visitWhiteSpace(IndentationRule.kt:174) ~[diktat-rules-0.1.4.jar:na]
	at org.cqfn.diktat.ruleset.rules.files.IndentationRule.access$visitWhiteSpace(IndentationRule.kt:57) ~[diktat-rules-0.1.4.jar:na]
	at org.cqfn.diktat.ruleset.rules.files.IndentationRule$checkIndentation$1.invoke(IndentationRule.kt:156) ~[diktat-rules-0.1.4.jar:na]
	at org.cqfn.diktat.ruleset.rules.files.IndentationRule$checkIndentation$1.invoke(IndentationRule.kt:57) ~[diktat-rules-0.1.4.jar:na]
```

## Environment information
* diktat version: 0.1.4 (same for 0.1.5)

**Comment by petertrr** [comment]
This is because of interaction with CompactInitializationRule. If property assignments are wrapped into `apply`, there is not error.
