### ISSUE TITLE
diKTat should not fail on missing configuration. It should raise a warning in this case

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#72]
[DEBUG] Internal Error (diktat-ruleset:package-naming)
com.pinterest.ktlint.core.RuleExecutionException: java.util.NoSuchElementException: Key domainName is missing in the map.
        at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:177)
        at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:43)
        at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:246)
        at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:43)
        at com.pinterest.ktlint.core.KtLint.visit(KtLint.kt:572)
        at com.pinterest.ktlint.core.KtLint.access$visit(KtLint.kt:43)
        at com.pinterest.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:244)
        at com.pinterest.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:43)
        at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:162)
        at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:51)

**Comment by petertrr** [comment]
Already closed
