### ISSUE TITLE
IdentifierNaming#checkObjectNaming throws NPE on checking companion object

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#84]
```
   [ktlint] Caused by: kotlin.KotlinNullPointerException
   [ktlint] 	at org.cqfn.diktat.ruleset.rules.IdentifierNaming.checkObjectNaming(IdentifierNaming.kt:185)
   [ktlint] 	at org.cqfn.diktat.ruleset.rules.IdentifierNaming.visit(IdentifierNaming.kt:69)
   [ktlint] 	at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:167)
   [ktlint] 	... 20 more
```

Same occurs on anonymous objects
```
object : Rule("astnode-utils-test") {
                                    override fun visit(node: ASTNode,
```

**Comment by akuleshov7** [comment]
fixed in https://github.com/cqfn/diKTat/pull/100
