### ISSUE TITLE
NullPointerException: prevNode must not be null

### ISSUE THREAD

**Issue by Cheshiriks** [cqfn/diKTat#912]
The exception occurs on the project RxKotlin

[ERROR] 2021-06-09 13:20:38 Internal error has occurred in horizontal-whitespace. Please make an issue on this bug at https://github.com/cqfn/diKTat/.
java.lang.NullPointerException: prevNode must not be null
        at org.cqfn.diktat.ruleset.rules.chapter3.files.WhiteSpaceRule.handleLbrace(WhiteSpaceRule.kt:196)
        at org.cqfn.diktat.ruleset.rules.chapter3.files.WhiteSpaceRule.logic(WhiteSpaceRule.kt:116)
        at org.cqfn.diktat.ruleset.rules.DiktatRule.visit(DiktatRule.kt:46)
        at com.pinterest.ktlint.core.KtLint$format$1.invoke(KtLint.kt:271)
        at com.pinterest.ktlint.core.KtLint$format$1.invoke(KtLint.kt:23)
        at com.pinterest.ktlint.core.KtLint$visitor$2$2.invoke(KtLint.kt:212)
        at com.pinterest.ktlint.core.KtLint$visitor$2$2.invoke(KtLint.kt:23)

**Comment by petertrr** [comment]
Please provide commit hash, on which the issue can be reproduced. We should implement #870 asap.

**Comment by kentr0w** [comment]
Couldn't reproduce bug with `diktat version: 0.6.2`
