### ISSUE TITLE
KotlinParseException: Your text is not valid

### ISSUE THREAD

**Issue by Cheshiriks** [cqfn/diKTat#914]
The exception occurs on the project okhttp

[ERROR] 2021-06-09 16:15:57 Internal error has occurred in class-compact-initialization. Please make an issue on this bug at https://github.com/cqfn/diKTat/.
org.cqfn.diktat.ruleset.utils.KotlinParseException: Your text is not valid
        at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode(KotlinParser.kt:75)
        at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode$default(KotlinParser.kt:75)
        at org.cqfn.diktat.ruleset.rules.chapter6.classes.CompactInitialization.getOrCreateApplyBlock(CompactInitialization.kt:124)
        at org.cqfn.diktat.ruleset.rules.chapter6.classes.CompactInitialization.moveAssignmentIntoApply(CompactInitialization.kt:80)
        at org.cqfn.diktat.ruleset.rules.chapter6.classes.CompactInitialization.access$moveAssignmentIntoApply(CompactInitialization.kt:30)
        at org.cqfn.diktat.ruleset.rules.chapter6.classes.CompactInitialization$handleProperty$2$1.invoke(CompactInitialization.kt:72)
        at org.cqfn.diktat.ruleset.rules.chapter6.classes.CompactInitialization$handleProperty$2$1.invoke(CompactInitialization.kt:71)
        at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix(Warnings.kt:259)
        at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix$default(Warnings.kt:201)

**Comment by akuleshov7** [comment]
@Cheshiriks please find the place of this bug

**Comment by kentr0w** [comment]
Couldn't reproduce bug with `diktat version: 0.6.2`

**Comment by Cheshiriks** [comment]
Example:

'''
class Foo() {

    fun Fuu() {
        logger.log(
            "<-- ${response.code}${if (response.message.isEmpty()) "" else ' ' + response.message} ${response.request.url} (${tookMs}ms${if (!logHeaders) ", $bodySize body" else ""})")

    }
    
}
'''
