### ISSUE TITLE
Internal error on gradle script

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#994]
## Describe the bug
```kotlin
import org.cqfn.save.buildutils.configurePublishing
import org.gradle.kotlin.dsl.dependencies
import org.gradle.kotlin.dsl.kotlin
import org.gradle.kotlin.dsl.project
import org.jetbrains.kotlin.gradle.targets.jvm.tasks.KotlinJvmTest
//import org.jetbrains.kotlin.gradle.dsl.jvm

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
}

kotlin {
    jvm {
        compilations.all {
            kotlinOptions {
                jvmTarget = "11"
                freeCompilerArgs = freeCompilerArgs + "-Xjvm-default=all"
            }
        }
    }
    val nativeTargets = listOf(linuxX64(), mingwX64(), macosX64())

    /**
     * Common structure for MPP libraries:
     * common
     * |
     * nonJs
     * / \
     * native JVM
     * / | \
     * linux mingw macos
     */
    sourceSets {
        all {
            languageSettings.useExperimentalAnnotation("kotlin.RequiresOptIn")
            languageSettings.useExperimentalAnnotation("okio.ExperimentalFileSystem")
        }
        val commonMain by getting
        val commonTest by getting
        val commonNonJsTest by creating {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
//                implementation("com.squareup.okio:okio-fakefilesystem-multiplatform:${Versions.okio}")
            }
        }
        val jvmTest by getting {
            dependsOn(commonNonJsTest)
            dependencies {
                implementation(kotlin("test-junit5"))
                implementation("org.junit.jupiter:junit-jupiter-engine:${Versions.junit}")
            }
        }
        val nativeMain by creating {
            dependsOn(commonMain)
        }
        val nativeTest by creating {
            dependsOn(commonTest)
        }
        nativeTargets.forEach {
            getByName("${it.name}Main").dependsOn(nativeMain)
        }
        nativeTargets.forEach {
            getByName("${it.name}Test").dependsOn(nativeTest)
            getByName("${it.name}Test").dependsOn(commonNonJsTest)
        }
    }
}

configurePublishing()

tasks.withType<KotlinJvmTest> {
    useJUnitPlatform()
}
```
produces the following:
```
[ERROR] 2021-07-22 16:04:48 Internal error has occurred in rule [kdoc-comments-codeblocks-formatting]. Please make an issue on this bug at https://github.com/cqfn/diKTat/. 
                       As a workaround you can disable these inspections in yml config: <[COMMENT_WHITE_SPACE, FIRST_COMMENT_NO_BLANK_LINE, IF_ELSE_COMMENTS, WRONG_NEWLINES_AROUND_KDOC]>.
                       Root cause of the problem is in [...\save\buildSrc\src\main\kotlin\kotlin-library.gradle.kts] file.
java.lang.NullPointerException
	at org.cqfn.diktat.ruleset.rules.chapter2.kdoc.CommentsFormatting.isFirstComment(CommentsFormatting.kt:323)
	at org.cqfn.diktat.ruleset.rules.chapter2.kdoc.CommentsFormatting.basicCommentsChecks(CommentsFormatting.kt:107)
	at org.cqfn.diktat.ruleset.rules.chapter2.kdoc.CommentsFormatting.handleEolAndBlockComments(CommentsFormatting.kt:97)
	at org.cqfn.diktat.ruleset.rules.chapter2.kdoc.CommentsFormatting.logic(CommentsFormatting.kt:67)
	at org.cqfn.diktat.ruleset.rules.DiktatRule.visit(DiktatRule.kt:50)
```

## Environment information
* diktat version: 1.0.0-rc.2

**Comment by petertrr** [comment]
The minimal reproducer:
```kotlin
import org.gradle.kotlin.dsl.project
//import org.jetbrains.kotlin.gradle.dsl.jvm

plugins

```
Turns out, we crash if some imports are commented in kts file.
